# Praca domowa nr 2
## Justyna Jankowiak

In [1]:
#ładowanie numpy
import numpy as np

#### 1. Zadanie 1
Przy uzyciu petli napisz funkcję `movingavg()`, która dla wektora $x$ o $n$ elementach oraz nieparzystej liczby naturalnej $k$ wyznaczy $k$-średnią ruchomą, $k < n$, tj. ciag $(w_1,\dots,w_{n-k+1})$, dla którego $w_i=\sum_{j=1}^k x_{i+j-1}/k$.

In [2]:
def movingavg(x, k):
    """
    Funckja 'movingavg' przyjmuje dwa argumenty:
    - wektor x o długości n
    - liczbę naturalną k, nieparzystą i mniejszą od n
    Funkcja zwraca wektor o długości n - k + 1, na i-tym miejscu wektora jest i-ta średnia ruchoma (z k elementów)
    """ 
    assert isinstance(x, np.ndarray), "x nie jest wektorem!"
    n = len(x)
    assert int(k) == k and k >=1, "k nie jest liczbą naturalną!"
    assert k % 2 != 0, "k nie jest liczbą nieparzystą!"
    assert k < n, "k musi być mniejsze od n (długość wektora x)"
    
    w = np.zeros(n - k + 1)
    for i in range(0, n - k + 1):
        w[i] = np.sum(x[i:(i + k)])/k
    return w

In [3]:
movingavg(np.array([1, 4, 5, 6, 4]), 3)

array([ 3.33333333,  5.        ,  5.        ])

In [4]:
x = np.random.rand(30)
print(x)
movingavg(x, 5)

[ 0.87227546  0.08986752  0.67431078  0.78335044  0.53470222  0.92283163
  0.92095     0.71085267  0.6292328   0.4321097   0.38883237  0.04613963
  0.80465012  0.94312483  0.79962539  0.24876326  0.01013801  0.99782507
  0.12662217  0.60478387  0.91770889  0.06795882  0.72546889  0.27958276
  0.48919012  0.82944781  0.16994086  0.41602822  0.55821179  0.24781765]


array([ 0.59090129,  0.60101252,  0.76722902,  0.77453739,  0.74371387,
        0.72319536,  0.61639551,  0.44143343,  0.46019292,  0.52297133,
        0.59647447,  0.56846065,  0.56126032,  0.59989532,  0.43659478,
        0.39762648,  0.5314156 ,  0.54297977,  0.48850853,  0.51910065,
        0.4959819 ,  0.47832968,  0.49872609,  0.43683796,  0.49256376,
        0.44428927])

#### 2. Zadanie 2
Napisz funkcje `logiderle()`, która jako argumenty przyjmuje równoliczne wektory całkowitoliczbowe $i$, $j$ oraz wartość całkowitą $n$. Jeśli dla każdego możliwego $l$ nie zachodzi $1 \le i_l \le j_l \le n$ oraz $i_l > j_{l-1}$, natychmiast zakończ działanie błędem (raise Exception("komunikat")). Funkcja ma generować $n$-elementowy wektor logiczny $w$ taki, że $w_l == \mathtt{True}$ wtw $(\exists p)$ $l\in[i_p; j_p]$. Dla przykładu, jeśli $n=7$, $\mathtt{i}=(1, 4)$, $\mathtt{j}=(1, 6)$, to w wyniku powinniśmy otrzymać łaskawie $(\mathtt{True},\mathtt{False},\mathtt{False}, \mathtt{True},\mathtt{True},\mathtt{True},\mathtt{False})$.

In [5]:
def logiderle(i, j, n):
    """
    Funkcja przyjmuje 3 argumenty:
    - i - wektor całkowitoliczbiwy
    - j - wektor całkowitoliczbowy takiej samej długości jak i oraz taki, że każdy element jest większy bądź równy
    od odpowiadającemu mu elementowi z i
    - n - liczba naturalna
    Funkcja zwraca n-elementowy wektor logiczny taki, że na l-tym miejscu jest True, jeżeli l należy do [i_p, j_p]
    dla pewnego p.
    """
    assert isinstance(i, np.ndarray), "i nie jest wektorem!"
    assert isinstance(j, np.ndarray), "j nie jest wektorem!"
    assert np.all(np.equal(np.mod(i, 1), 0)), "i nie jest wektorem całkowitoliczbowym!"
    assert np.all(np.equal(np.mod(j, 1), 0)), "j nie jest wektorem całkowitoliczbowym!"
    assert int(n) == n and n >= 1, "n nie jest liczbą naturalną!"
    assert len(i) == len(j), "wektory i i j są różnej długości!"
    assert np.all(i <= j), "każda wartość w wektorze i musi być mniejsza bądź równa od odpowiadajacej \
    jej wartości w wektorze j!"
    
    #zdefiniowanie w wektorze w pola dtype jako bool gwarantuje mi wynik jako wektor True/False a nie 0/1
    w = np.zeros(n, dtype = bool)
    #zakładam, ze indeksowanie od 1
    for k in range(1, n + 1): 
        log = np.any(np.logical_and(k >= i, k <= j))
        w[k - 1] = log
    return w

In [6]:
i = np.array([1, 4])
j = np.array([1, 6])
n = 7
logiderle(i, j, n)

array([ True, False, False,  True,  True,  True, False], dtype=bool)

In [7]:
np.repeat(False, 5)

array([False, False, False, False, False], dtype=bool)

#### 3. Zadanie 3
Napisz funkcję `gendyskr()`, która jako argumenty przyjmuje:

* wartość całkowitą dodatnią $n$,
* $k$-elementowy wektor liczbowy $x$ o unikalnych wartościach,
* $k$-elementowy wektor prawdopodobieństw $p$ - jeśli wartości w $p$ nie sumują się do 1, należy go przed wykonaniem obliczeń unormować.

Naszym zadaniem jest implementacja algorytmu, który generuje $n$-elementową pseudolosową próbkę z rozkładu dyskretnego zmiennej losowej $X$ takiego, że $\Pr(X=x_i)=p_i$ $(\forall i=1,\dots,k)$. Pojedynczą wartość otrzymujemy tak oto:

1. Wygeneruj obserwację $u$ z rozkładu jednostajnego na $(0,1)$. 
2. Znajdź $m\in{1,\dots,k}$ takie, że $u\in(\sum_{j=1}^{m-1} p_{j}, \sum_{j=1}^m p_{j}]$, przy założeniu $\sum_{j=1}^0 \cdot =0$. 
3. Zwróć $x_m$ jako wynik.

In [8]:
def gendyskr(n, x, p):
    """
    Funkcja przyjmuje trzy argumenty:
    - n - liczbą naturalną, wielkość próby
    - x - wektor unikalnych wartości
    - p - wagi dla poszczególnych wartości z wektora x 
    (gdy jest unormowany p możemy przyjąć jako wektor prawdopodobieństw)
    Funkcja zwraca n-elementową próbę z rozkładu dyskretnego o wartościach x i prawdopodobieństwach p
    """
    assert int(n) == n and n >= 1, "n nie jest liczbą całkowitą dodatnią"
    assert isinstance(x, np.ndarray), "x nie jest wektorem!"
    k = len(x)
    assert len(set(x)) == k, "x nie jest wektorem o unikalnych wartościach!"
    assert len(p) == k, "wektory p i k nie są tej samej długości"
    
    #jeżeli potrzeba to normalizujemy wektor p
    sump = np.sum(p)
    if sump != 1: 
        p = p/sump
    
    cumsump = np.append(0, np.cumsum(p))
    value = np.zeros(n)
    for i in range(0, n):
        #generujemy obserwację z rozkładu jednostajnego (0, 1)
        u = np.random.uniform()
        #znajdujemy odpowiedni indeks
        index = np.max(np.where(u > cumsump))
        #zwracamy m-tą wartość wektora x
        value[i] = x[index]
    return value

In [9]:
n = 20
x = np.array([1, 2, 3, 4, 5, 6])
p = np.array([0, 0, 0.5, 0.9, 0, 0.2])
gendyskr(n, x, p)

array([ 4.,  3.,  4.,  3.,  4.,  4.,  4.,  3.,  4.,  3.,  6.,  3.,  3.,
        4.,  3.,  3.,  4.,  3.,  4.,  4.])

#### 4. Zadanie 4
Zaimplementuj algorytm sortowania przez scalanie danej tablicy liczb rzeczywistych.

In [10]:
def mergesort(array):
    """
    Funkcja przyjmuje wektor nieposortowanych wartości rzeczywistych
    Funkcja zwraca wektor posortowanych wartości (za pomocą algorytmu sortowania przez scalanie)
    """
    assert isinstance(array, np.ndarray), "array nie jest wektorem!"
    assert len(array) >= 1, "array powinna mieć długość większą bądź równą 1!" 
    
    if len(array) >= 2:
        #wyznaczamy środek i dzielimy względem niego tablicę na dwie cześci - prawą i lewą
        mid = len(array) // 2
        left = array[:mid]
        right = array[mid:]
        #rekurencyjnie zapuszczamy algorytm na połówkach
        left = mergesort(left)
        right = mergesort(right)
        #sklejamy posortowane już części
        return merge(left, right)
    else:
        return array
    
def merge(arrayl, arrayr):
    """
    Funkcja "skleja" dwie posortowane już tablice
    """
    merged = np.array([])
    idl = 0
    idr = 0 
    #dopóki w obu tablicach mamy niewykorzystane elementy to porządkujemy je względem siebie
    while idl < len(arrayl) and idr < len(arrayr):
        if arrayl[idl] <= arrayr[idr]:
            merged = np.append(merged, arrayl[idl])
            idl += 1
        else:
            merged = np.append(merged, arrayr[idr])
            idr += 1
    #ale możemy być tak, że elementy z jednej tablicy skończą się wcześniej niż w drugiej
    #to znaczy, że możemy wtedy dokleić wszystkie niewykorzystane elementy tablicy na koniec
    while idl < len(arrayl):
        merged = np.append(merged, arrayl[idl])
        idl +=1
    while idr < len(arrayr):
        merged = np.append(merged, arrayr[idr])
        idr +=1
    return merged

In [11]:
mergesort(np.array([54, 7, 8, 2.5, 3, 45.12, 5, 7]))

array([  2.5 ,   3.  ,   5.  ,   7.  ,   7.  ,   8.  ,  45.12,  54.  ])

In [12]:
mergesort(np.array([3, 4, 3, 3]))

array([ 3.,  3.,  3.,  4.])

#### 5. Zadanie 6
Napisz funkcję `liniowa()`, która jako argumenty przyjmuje:

* posortowany rosnąco $n$-elementowy wektor liczbowy $x$,
* $n$-elementowy wektor liczbowy $y$ (dowolny),
* $k$-elementowy wektor liczbowy $z$ o wartościach z przedziału $[x_1, x_n)$.

Funkcja ta powinna zwracać $k$-elementowy wektor, którego $i$-ty element jest wynikiem obliczenia wartości funkcji kawałkami liniowej (tj. łamanej) interpolującej liniowo punkty $(x_1,y_1),\dots,(x_n,y_n)$ w punkcie $z_i$. Formalnie, jeśli $j\in{1,\dots,n-1}$ jest taki, że $x_j \le z_i < x_{j+1}$, to $i$-tą wartością wynikową będzie $y_j + (y_{j+1}-y_j)(z_i-x_j)/(x_{j+1}-x_j)$.

In [13]:
def liniowa(x, y, z):
    """
    Funkcja przyjmuje trzy argumenty:
    - x - wektor uporządkowanych rosnąco wartości
    - y - dowolny wektor długości takiej jak x
    - wektor z o wartościach z przedziału [x1, xn)
    Funkcja zwraca wektor długości takiej jak z, którego i-ty element jest wynikiem obliczenia wartości funkcji
    kawałkami liniowej interpolującej liniowo punkty (x1, y1), ..., (xn, yn) w punkcie zi.
    """
    assert isinstance(x, np.ndarray), "array nie jest wektorem!"
    assert isinstance(y, np.ndarray), "array nie jest wektorem!"
    assert isinstance(z, np.ndarray), "array nie jest wektorem!"
    n = len(x)
    assert len(y) == n, "wektory x i y nie są takiej samej długości!"
    assert np.all(x == np.sort(x)), "wektor x nie jest posortowany!"
    assert np.all(np.logical_and(z >= x[0], z < x[n - 1])), "z przyjmuje inne wartości niż z przedziału [x_1, x_n)!"

    k = len(z)
    inter = np.zeros(k)
    for i in range(0, k):
        zz = z[i]
        index = np.max(np.where(zz >= x))
        inter[i] = y[index] + ((y[index + 1] - y[index]) * (zz - x[index]))/(x[index + 1] - x[index])
    return inter

In [14]:
x = np.array([0, 1, 2, 3])
y = x ** 2
z = np.linspace(0, 2.9, 10)
print(z)
liniowa(x, y, z)

[ 0.          0.32222222  0.64444444  0.96666667  1.28888889  1.61111111
  1.93333333  2.25555556  2.57777778  2.9       ]


array([ 0.        ,  0.32222222,  0.64444444,  0.96666667,  1.86666667,
        2.83333333,  3.8       ,  5.27777778,  6.88888889,  8.5       ])

#### 6. Zadanie 8
Implement the $k$-means clustering algorithm for a given $n\times m$ matrix: 

1.  Choose initial cluster centroids, $\mu_i$, $i=1,\dots,k$ (component-wise means). 
2. Assign each point to the nearest centroid.
3. Recalculate cluster centroids by computing the means $\mu_i$ of all the points assigned to each cluster. 
4. If convergence not reached: Goto 2.

In [37]:
def first_centroid(M, k):
    #generujemy piersze środki klastrów jako średnie z próbek losowych punktów
    n = M.shape[0]
    m = M.shape[1]
    cent = [[]] * k
    for i in range(0, k):
        #losowe ~20% obserwacji
        probka = np.random.choice(n, n // 5)
        #wyliczamy ich średnią
        cent[i] = [np.mean(M[probka, x]) for x in range(0, m)]
    return np.array(cent)

def find_class(M, means):
    n = M.shape[0]
    m = M.shape[1]
    clas = np.zeros(n)
    for i in range(0, n):
        #wektor odległości między punktem a środkami 
        distance = [(np.sum((M[i] - x) ** 2)) ** 0.5 for x in means]
        #wybrana klasa to ta z najmniejsża odległością
        klasa = np.where(distance == min(distance))[0][0]
        clas[i] = klasa
    return clas

def recalculate(M, cent, k):
    #ponowne policzenie środków klastró gdy mamy już przypisane klasy
    m = M.shape[1]
    nowe_sr = [[]] * k
    for i in range(0, k):
        ktore_wiersze = (cent == i)
        sr = [np.mean(M[ktore_wiersze, x]) for x in range(0, m)]
        nowe_sr[i] = sr
    return np.array(nowe_sr)

def kmeans(M, k, maxiter = 20):
    """
    Funcja przyjmuje dwa argumenty
    - M - macierz n x m
    - k - ilość klastrów, na które chcemy podzielić
    Dodatkwo ustawiona jest liczba maksymalnych iteracji na 20
    Funkcja zwraca wektor z wyliczonymi średnimi dla poszczególnych klastrów 
    oraz wektor klas, do których zostałe przypisane pszczególne punkty
    """
    assert len(M.shape) == 2, "M nie jest macierzą!"
    assert int(k) == k and k > 1, "liczba klastrów musi być co najmniej 2!"
    assert int(maxiter) == maxiter and maxiter > 0, "liczba iteracji musi być co najmniej 1!"
    
    cent = first_centroid(M, k)
    clas = find_class(M, cent)
    for i in range(maxiter):
        nowe_cent = recalculate(M, clas, k)
        diff = np.zeros(k)
        for j in range(0, k):
            diff[j] = (np.sum((cent[j] - nowe_cent[j]) ** 2)) ** 0.5
        diffmax = max(diff)
        if diffmax < 0.001:
            break
        else:
            cent = nowe_cent
            nowe_klasy = find_class(M, cent)
            nowe_cent = recalculate(M, nowe_klasy, k)
    return [nowe_cent, nowe_klasy]

In [39]:
#wygenerowanie odpowiedniej macierzy
A = np.random.multivariate_normal((3, 3), np.array([[0.05, 0], [0, 0.3]]), 50)
B = np.random.multivariate_normal((2, 1), np.array([[0.1, 0], [0, 0.1]]), 50)
C = np.random.multivariate_normal((1, 3), np.array([[0.2, 0], [0, 0.4]]), 50)
M = np.vstack((A, B, C))

wynik = kmeans(M, k = 3)
print(wynik)
kolory = ['g' for i in range(0, len(wynik[1]))]
for i in range(0, len(wynik[1])):
    if wynik[1][i] == 1: 
        kolory[i] = 'y'
    if wynik[1][i]== 2:
        kolory[i] = 'b'

import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.scatter(M[:, 0], M[:, 1], color = kolory)
plt.show()

[array([[ 1.12604046,  3.29654835],
       [ 1.44436138,  0.96614781],
       [ 2.52558031,  1.92351128]]), array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  0.,  2.,
        2.,  0.,  2.,  2.,  0.,  2.,  0.,  2.,  0.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  0.,  2.,  2.,  2.,  2.,  2.,  2.,  0.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  1.,
        1.,  1.,  1.,  2.,  1.,  1.,  1.,  2.,  1.,  2.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  2.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,
        1.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.])]


#### 7. Zadanie 9
Macierz kwadratowa $E$ o rozmiarze $n\times n$ i elementach calkowitych nieujemnych może reprezentować graf skierowany ważony $G=(\{0,1,\dots,n-1\}, E)$. Zaimplementuj algorytm Dijkstry znajdowania najkrótszej ścieżki między dwoma danymi wierzchołkami $i,j\in{0,1,\dots,n-1}$ w $G$.

In [22]:
INF = 1000 #"nieskończoność"

def min_distance(dist, Q):
    #funkcja szuka wierzchołka z najmniejszą odległością spośród wierzchołków będących jeszcze w puli
    mini = INF
    for v in range(len(dist)):
        if Q[v] == False and dist[v] <= mini:
            mini = dist[v]
            mini_id = v
    return mini_id

def dijkstra(G, source1, source2):
    """
    Funcja przyjmuje trzy argumenty
    - macierz G opisująca odległości w grafie (symetryczna)
    - source1 - indeks wierzchołka1
    - source2 - indeks wierzchołka2
    Funkcja wypisuje najmniejszą odległość pomiędzy tymi wierzchołkami wyliczoną algorytmem Dijkstry
    """
    assert len(G.shape) == 2, "G nie jest macierzą!"
    assert G.shape[0] == G.shape[1], "G musi być macierzą kwadratową!"
    assert source1 in range(G.shape[0]) and source2 in range(G.shape[0]), "Błędne indeksy wierzchołków!"
    V = G.shape[1]
    dist = np.repeat(INF, V)
    dist[source1] = 0
    Q = np.zeros(V, dtype = bool)
    
    for i in range(0, V - 1):
        #wybieramy wierzchołek o najmniejszej odległości, który jest jeszcze w puli
        u = min_distance(dist, Q)
        #oznaczamy go jako już wybrany
        Q[u] = True
        for v in range(0, V):
            #aktualizacja odległości dla tych, dla których odległość idące przez wierzchołek u jest mniejsza
            if Q[v] == False and G[u, v] > 0 and dist[u] != INF and dist[u] + G[u, v] < dist[v]:
                dist[v] = dist[u] + G[u, v]
    print("Dystans między wierzchołkiem " + str(source1) + " a wierzchołkiem " 
          + str(source2) + " wynosi " + str(dist[source2]) + ".")

In [23]:
G = np.array([[0, 4, 0, 0, 0, 0, 0, 8, 0],
             [4, 0, 8, 0, 0, 0, 0, 11, 0],
             [0, 8, 0, 7, 0, 4, 0, 0, 2],
             [0, 0, 7, 0, 9, 14, 0, 0, 0],
             [0, 0, 0, 9, 0, 10, 0, 0, 0],
             [0, 0, 4, 0, 10, 0, 2, 0, 0],
             [0, 0, 0, 14, 0, 2, 0, 1, 6],
             [8, 11, 0, 0, 0, 0, 1, 0, 7],
             [0, 0, 2, 0, 0, 0, 6, 7, 0]])
dijkstra(G, 0, 1);

Dystans między wierzchołkiem 0 a wierzchołkiem 1 wynosi 4.


Nie lubie grafów, więc reszta zadań to algorytmy nie wymienione w liście zadań.
#### 8. Zadanie
Zaimplementuj algorytm IWLS
(https://en.wikipedia.org/wiki/Iteratively_reweighted_least_squares).

In [24]:
def IWLS(x, y, max_iter):
    """
    Funkcja przyjmuje 3 argumenty:
    - macierz x (wartości objaśniających)
    - wektor y wartości objaśnianych
    - max_iter - maksymalna liczba iteracji
    Za pomocą algorytmy IWLS obliczane są współczynniki w równaniu y ~ x1 + x2 + ... + xp (razem z wyrazem wolnym)
    Funkcja zwraca wektor współczynników b
    """
    n = x.shape[0]
    p = x.shape[1]
    
    assert len(y) == n, "Błędny wymiar wektora odpowiedzi!"
    assert int(max_iter) == max_iter and max_iter > 0, "Liczba iteracji musi być liczbą naturalną!"
    
    eps = 1e-10
    oldpr = np.repeat(1, n)
    b = np.zeros(p + 1)
    X = np.column_stack((np.repeat(1, n), x))
    
    for i in range(max_iter):
        bX = np.dot(X, b)
        pr = 1/(1 + np.exp(-bX))
        W = np.zeros((n, n))
        W[range(n), range(n)] = pr * (1 - pr)
        b = b + np.dot(np.dot(np.linalg.inv(np.dot(np.dot(np.matrix.transpose(X), W), X)), np.matrix.transpose(X)), y - pr)
    
        if np.sum(np.abs(oldpr - pr)) < n * eps:
            break
        oldpr = pr
    return b

In [25]:
x = np.random.rand(20, 5)
y = np.random.binomial(1, 0.75, size = 20)
IWLS(x, y, 500)

array([   2.02465455,  172.87638772,  597.0070275 ,  292.62770623,
       -418.15442155, -266.05412591])

#### 9. Zadanie
Zaimplementuj dekompozycję LU (https://en.wikipedia.org/wiki/LU_decomposition)

In [26]:
def LU(A):
    """
    Funkcja przyjmuje jeden argument - macierz kwadratową A
    Zwraca dwie macierze dolną i górną trójkątną, zgodnie z rozkładem LU
    """
    n = A.shape[0] 
    assert A.shape[1] == n, "Macierz A musi być macierzą kwadratową!"
    
    L = np.zeros((n,n)) 
    U = np.zeros((n,n)) 
    U[:] = A 
    L[range(n), range(n)] = 1
    for i in range(n - 1):
        for j in range(i + 1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j, i:] = U[j, i:] - L[j, i] * U[i, i:]
            U[j, i] = 0
    return [L, U]

In [27]:
A = np.array([[4, 3], [6, 3]])
LU(A)

[array([[ 1. ,  0. ],
        [ 1.5,  1. ]]), array([[ 4. ,  3. ],
        [ 0. , -1.5]])]

#### 10. Zadanie
Zaimplementuj dekompozycję Cholewskiego (https://en.wikipedia.org/wiki/Cholesky_decomposition).

In [28]:
def cholesky(A):
    """
    Funkcja przymuje macierz kwadratową i symetryczną A.
    Zwraca macierz L - dolną z dekompozycji Cholewskiego (druga to jej odbicie)
    """
    n = A.shape[0]
    assert A.shape[1] == n, "Macierz nie jest kwadratowa!"
    
    L = np.zeros((n, n))
    for i in range(n):
        for k in range(i + 1):
            suma = sum(L[i, j] * L[k, j] for j in range(k))
            if (i == k):
                L[i, k] = (A[i, i] - suma) ** 0.5
            else:
                L[i, k] = (1.0 / L[k, k] * (A[i, k] - suma))
    return L

In [29]:
A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
cholesky(A)

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])